### ISSUE TITLE
Add CI to validate categories

### ISSUE THREAD

**Issue by bstansberry** [wildfly/wildfly-proposals#568]
I have no idea how practical this is, but it would be good to have a github action that validates PRs for the presence of the 'categories' front matter, including at least one category, and that all declared categories map to one of the _data/categories.yaml entries.

I've spent a lot of time today fixing up various analysis docs when preparing the WildFly 32 release announcement.

**Comment by jmesnil** [comment]
@bstansberry I've done something similar on a test project and I'll have a look at it.

I considering also expanding these checks for things required by an analysis document (link to issue tracker, stability level) in a second time.
Depending on the evolution of our process, I'd like to move more metadata to the front matter for further validation (eg reviewer, approved, outside_perspective assignees)
